services:

  mongo:
    image: mongo:7
    container_name: tradefy-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tradefy

  redis:
    image: redis:7
    container_name: tradefy-redis
    ports:
      - "6379:6379"
    networks:
      - tradefy

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
    networks:
      - tradefy

  frontend:
    build: ./frontend
    container_name: tradefy-frontend
    networks:
      - tradefy

  nginx:
    image: nginx:alpine
    container_name: tradefy-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - tradefy

volumes:
  mongo_data:

networks:
  tradefy:
    driver: bridge
